---
name: Test package
on: [pull_request]  # yamllint disable-line rule:truthy
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: pip

      - name: Install tox
        run: pip install tox

      - name: Cache tox environments
        uses: actions/cache@v1
        with:
          path: .tox
          key: tox|${{ hashFiles('tox.ini')}}

      - name: Test package
        run: tox
