---
name: Code coverage
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    paths:
      - '**.py'
      - 'pyproject.toml'

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install poetry
        run: pip install poetry pytest pytest-cov

      - name: Install package from source
        run: poetry install

      - name: Run pytest
        run: pytest --cov=prototype_python_library --cov-report=xml tests/

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
